Presentation/Nop.Web/Administration/Models/FeaturesLists/FeaturesListItemModel.cs
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FluentValidation.Attributes;
using Nop.Admin.Validators.FeaturesLists;

namespace Nop.Admin.Models.FeaturesLists
{
    public partial class FeaturesListItemModel : BaseNopEntityModel
    {
        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.FeaturesListId")]
        [AllowHtml]
        public int FeaturesListId { get; set; }

        [UIHint("Picture")]
        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.PictureId")]
        [AllowHtml]
        public int PictureId { get; set; }
        public string PictureURL { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.Comment")]
        [AllowHtml]
        public string Comment { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.ArabicComment")]
        [AllowHtml]
        public string ArabicComment { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.Text")]
        [AllowHtml]
        public string Text { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.ArabicText")]
        [AllowHtml]
        public string ArabicText { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.URL")]
        [AllowHtml]
        public string URL { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.DisplayOrder")]
        [AllowHtml]
        public int DisplayOrder { get; set; }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.Visible")]
        [AllowHtml]
        public bool Visible { get; set; }
    }
}

Presentation/Nop.Web/Administration/Models/FeaturesLists/FeaturesListModel.cs
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FluentValidation.Attributes;
using Nop.Admin.Validators.FeaturesLists;

namespace Nop.Admin.Models.FeaturesLists
{
    [Validator(typeof(FeaturesListValidator))]
    public partial class FeaturesListModel : BaseNopEntityModel
    {
        public FeaturesListModel()
        {
            AddFeatureItem = new FeaturesListItemModel();
        }

        [NopResourceDisplayName("Admin.ContentManagement.FeaturesList.Fields.Name")]
        [AllowHtml]
        public string Name { get; set; }

        public FeaturesListItemModel AddFeatureItem { get; set; }
    }
}

Presentation/Nop.Web/Administration/Controllers/FeaturesListController.cs
using Nop.Admin.Models.Catalog;
using Nop.Admin.Models.FeaturesLists;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.FeaturesLists;
using Nop.Services.ExportImport;
using Nop.Services.FeaturesLists;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nop.Admin.Controllers
{
    public partial class FeaturesListController : BaseAdminController
    {
        #region Fields

        private readonly IFeaturesListService _featuresListService;
        private readonly IPictureService _pictureService;
        private readonly IStoreService _storeService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IAclService _aclService;
        private readonly IPermissionService _permissionService;
        private readonly CatalogSettings _catalogSettings;

        #endregion

        #region Constructors

        public FeaturesListController(IFeaturesListService featuresListService,
            IPictureService pictureService,
            IStoreService storeService,
            IStoreMappingService storeMappingService,
            IUrlRecordService urlRecordService,
            ILanguageService languageService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            ICustomerActivityService customerActivityService,
            IAclService aclService,
            IPermissionService permissionService,
            CatalogSettings catalogSettings)
        {
            this._featuresListService = featuresListService;
            this._pictureService = pictureService;
            this._storeService = storeService;
            this._storeMappingService = storeMappingService;
            this._urlRecordService = urlRecordService;
            this._languageService = languageService;
            this._localizationService = localizationService;
            this._localizedEntityService = localizedEntityService;
            this._customerActivityService = customerActivityService;
            this._aclService = aclService;
            this._permissionService = permissionService;
            this._catalogSettings = catalogSettings;
        }

        #endregion
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            return View();
        }

        [HttpPost]
        public ActionResult List(DataSourceRequest command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresList = _featuresListService.GetAllFeaturesList(command.Page - 1, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = featuresList.Select(x => x.ToModel()),
                Total = featuresList.TotalCount
            };

            return Json(gridModel);
        }

        public ActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var model = new FeaturesListModel();

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public ActionResult Create(FeaturesListModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var featuresList = model.ToEntity();
                _featuresListService.InsertFeaturesList(featuresList);

                //activity log
                _customerActivityService.InsertActivity("AddNewFeaturesList", _localizationService.GetResource("ActivityLog.AddNewFeaturesList"), featuresList.Name);

                SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.FeaturesList.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = featuresList.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresList = _featuresListService.GetFeaturesListById(id);
            if (featuresList == null)
                //No Features List found with the specified id
                RedirectToAction("List");

            var model = featuresList.ToModel();

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public ActionResult Edit(FeaturesListModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresList = _featuresListService.GetFeaturesListById(model.Id);
            if (featuresList == null)
                //No Features List found with the specified id
                RedirectToAction("List");

            if (ModelState.IsValid)
            {
                featuresList = model.ToEntity(featuresList);
                _featuresListService.UpdateFeaturesList(featuresList);

                //activity log
                _customerActivityService.InsertActivity("EditFeaturesList", _localizationService.GetResource("ActivityLog.EditFeaturesList"), featuresList.Name);

                SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.FeaturesList.Updated"));
                return continueEditing ? RedirectToAction("Edit", featuresList.Id) : RedirectToAction("List");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresList = _featuresListService.GetFeaturesListById(id);
            if (featuresList == null)
                //No Page found with the specified id
                return RedirectToAction("List");

            _featuresListService.DeleteFeaturesList(featuresList);

            //activity log
            _customerActivityService.InsertActivity("DeleteFeaturesList", _localizationService.GetResource("ActivityLog.DeleteFeaturesList"), featuresList.Name);

            SuccessNotification(_localizationService.GetResource("Admin.ContentManagement.FeaturesList.Deleted"));
            return RedirectToAction("List");
        }

        #region Features List Item

        [HttpPost]
        public ActionResult FeaturesListItemAdd(int FeaturesListId, int pictureId, string url, string comment, string arabicComment,
                                                string text, string arabicText, int displayOrder, bool visible)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresListItem = new FeaturesListItem()
            {
                FeaturesListId = FeaturesListId,
                PictureId = pictureId,
                URL = url,
                Comment = comment,
                ArabicComment = arabicComment,
                Text = text,
                ArabicText = arabicText,
                DisplayOrder = displayOrder,
                Visible = visible,
            };

            _featuresListService.InsertFeaturesListItem(featuresListItem);

            return Json(new { Result = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FeaturesListItemList(DataSourceRequest command, int FeaturesListId)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresListItems = _featuresListService.GetFeaturesListItemsByFeaturesListId(FeaturesListId);
            var featuresListItemsModel = featuresListItems.Select(x => x.ToModel()).ToList();
            foreach (var item in featuresListItemsModel)
            {
                item.PictureURL = _pictureService.GetPictureUrl(item.PictureId);
            }

            var gridModel = new DataSourceResult
            {
                Data = featuresListItemsModel,
                Total = featuresListItemsModel.Count
            };

            return Json(gridModel);
        }

        [HttpPost]
        public ActionResult FeaturesListItemUpdate(FeaturesListItemModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var featuresListItem = _featuresListService.GetFeaturesListItemById(model.Id);
            if (featuresListItem == null)
                throw new ArgumentException("No Features List Item found with the specified id");
            

Presentation/Nop.Web/Administration/Views/FeaturesList/Create.cshtml
@using Nop.Admin.Models.FeaturesLists;

@model FeaturesListModel
@{
    //page title
    ViewBag.Title = T("Admin.ContentManagement.FeaturesList.AddNew").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
            @T("Admin.ContentManagement.FeaturesList.AddNew") @Html.ActionLink("(" + T("Admin.ContentManagement.FeaturesList.BackToList") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

Presentation/Nop.Web/Administration/Views/FeaturesList/Edit.cshtml
@using Nop.Admin.Models.FeaturesLists;

@model FeaturesListModel
@{  
    //page title
    ViewBag.Title = T("Admin.ContentManagement.FeaturesList.EditFeaturesListDetails").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
            @T("Admin.ContentManagement.FeaturesList.EditFeaturesListDetails") - @Model.Name @Html.ActionLink("(" + T("Admin.ContentManagement.FeaturesList.BackToList") + ")", "List")
        </div>
        <div class="options">
            <input type="submit" name="save" class="k-button" value="@T("Admin.Common.Save")" />
            <input type="submit" name="save-continue" class="k-button" value="@T("Admin.Common.SaveContinue")" />
            <span id="featuresList-delete" class="k-button">@T("Admin.Common.Delete")</span>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@Html.DeleteConfirmation("featuresList-delete")

Presentation/Nop.Web/Administration/Views/FeaturesList/List.cshtml
@{  
    var gridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSize;

    //page title
    ViewBag.Title = T("Admin.ContentManagement.FeaturesList").Text;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
        @T("Admin.ContentManagement.FeaturesList")
    </div>
    <div class="options">
        <a href="@Url.Action("Create")" class="k-button">@T("Admin.Common.AddNew")</a>
    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            <div id="featuresList-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#featuresList-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("List", "FeaturesList"))",
                                    type: "POST",
                                    dataType: "json",
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            pageSize: @(gridPageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [{
                            field: "Name",
                            title: "@T("Admin.ContentManagement.FeaturesList.Fields.Name")",
                            width: 400
                        }, {
                            field: "Id",
                            title: "@T("Admin.Common.Edit")",
                            width: 100,
                            template: '<a href="Edit/#=Id#">@T("Admin.Common.Edit")</a>'
                        }]
                    });
                });
            </script>
        </td>
    </tr>
</table>

Presentation/Nop.Web/Administration/Views/FeaturesList/_CreateOrUpdate.FeaturesListItems.cshtml
@using Nop.Admin.Models.FeaturesLists;

@model FeaturesListModel


@if (Model.Id > 0)
{
    <div id="featuresListItems-grid"></div>

    <script>
        $(document).ready(function () {
            $("#featuresListItems-grid").kendoGrid({
                dataSource: {
                    type: "json",
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("FeaturesListItemList", "FeaturesList", new { FeaturesListId = Model.Id }))",
                            type: "POST",
                            dataType: "json"
                        },
                        @*create: {
                                url: "@Html.Raw(Url.Action("FeaturesListItemsInsert", "FeaturesList", new { FeaturesListId = Model.Id }))",
                                type: "POST",
                                dataType: "json"
                            },*@
                        update: {
                            url: "@Html.Raw(Url.Action("FeaturesListItemUpdate", "FeaturesList"))",
                            type: "POST",
                            dataType: "json"
                        },
                        destroy: {
                            url: "@Html.Raw(Url.Action("FeaturesListItemsDelete", "FeaturesList"))",
                            type: "POST",
                            dataType: "json"
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                        model: {
                            id: "Id",
                            fields: {
                                //FeaturesListId: { editable: false, type: "number" },
                                PictureURL: { editable: false, type: "string" },
                                URL: { editable: true, type: "string" },
                                Comment: { editable: true, type: "string" },
                                ArabicComment: { editable: true, type: "string" },
                                Text: { editable: true, type: "string" },
                                ArabicText: { editable: true, type: "string" },
                                DisplayOrder: { editable: true, type: "number" },
                                Visible: { editable: true, type: "boolean" },
                                PictureId: { editable: false, type: "number" },
                                Id: { editable: false, type: "number" }
                            }
                        }
                    },
                    requestEnd: function (e) {
                        if (e.type == "create" || e.type == "update") {
                            this.read();
                        }
                    },
                    error: function (e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    numeric: false,
                    previousNext: false,
                    info: false
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "PictureURL",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.PictureId")",
                    width: 150,
                    template: '<a href="#=PictureURL#" target="_blank"><img alt="#=PictureId#" src="#=PictureURL#" width="150" /><a/>',
                }, {
                    field: "URL",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.URL")",
                    width: 100,
                }, {
                    field: "Comment",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.Comment")",
                    width: 100,
                }, {
                    field: "ArabicComment",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.ArabicComment")",
                    width: 100,
                }, {
                    field: "Text",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.Text")",
                    width: 100,
                }, {
                    field: "ArabicText",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.ArabicText")",
                    width: 100,
                }, {
                    field: "DisplayOrder",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.DisplayOrder")",
                    width: 100,
                    //integer format
                    format: "{0:0}",
                }, {
                    field: "Visible",
                    title: "@T("Admin.ContentManagement.FeaturesList.Fields.Visible")",
                    width: 100,
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                }, {
                    command: [{
                        name: "edit",
                        text: "@T("Admin.Common.Edit")"
                    }, {
                        name: "destroy",
                        text: "@T("Admin.Common.Delete")"
                    }],
                    width: 200
                }]
            });
        });
    </script>

    <p>
        <strong>@T("Admin.ContentManagement.FeaturesList.AddNew")</strong>
    </p>

    <script type="text/javascript">

        $(document).ready(function () {
            $('#AddFeatureItem_Visible').val(false);
            $('#AddFeatureItem_Visible').click(function () {
                if($(this).is(':checked'))
                    $(this).val(true);
                else
                    $(this).val(false);
            });

            $('#addFeatureListItem').click(function () {
                var pictureId = $("#@Html.FieldIdFor(model => model.AddFeatureItem.PictureId)").val();
                var url = $("#@Html.FieldIdFor(model => model.AddFeatureItem.URL)").val();
                var comment = $("#@Html.FieldIdFor(model => model.AddFeatureItem.Comment)").val();
                var arabicComment = $("#@Html.FieldIdFor(model => model.AddFeatureItem.ArabicComment)").val();
                var text = $("#@Html.FieldIdFor(model => model.AddFeatureItem.Text)").val();
                var arabicText = $("#@Html.FieldIdFor(model => model.AddFeatureItem.ArabicText)").val();
                var displayOrder = $("#@Html.FieldIdFor(model => model.AddFeatureItem.DisplayOrder)").val();
                var visible = $("#@Html.FieldIdFor(model => model.AddFeatureItem.Visible)").val();

                if (pictureId == 0) {
                    alert('Upload picture first');
                    return;
                }

                $('#addFeatureListItem').attr('disabled', true);
                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("FeaturesListItemAdd", "FeaturesList"))",
                    data: { "FeaturesListId": @Model.Id, "pictureId": pictureId, "url": url, "comment": comment, "arabicComment": arabicComment, "text": text, "arabicText": arabicText, "displayOrder": displayOrder, "visible": visible},
                    success: function (data) {
                        var feturesListItemsGrid = $("#featuresListItems-grid");
                        feturesListItemsGrid.data('kendoGrid').dataSource.read();
                        $('#addFeatureListItem').attr('disabled', false);
                        var url = $("#@Html.FieldIdFor(model => model.AddFeatureItem.URL)").val("");
                        var comment = $("#@Html.FieldIdFor(model => model.AddFeatureItem.Comment)").val("");
                        var arabicComment = $("#@Html.FieldIdFor(model => model.AddFeatureItem.ArabicComment)").val("");
                        var text = $("#@Html.FieldIdFor(model => model.AddFeatureItem.Text)").val("");
                        var arabicText = $("#@Html.FieldIdFor(model => model.AddFeatureItem.ArabicText)").val("");
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert('Failed to add Feature List Item.');
                        $('#addFeatureListItem').attr('disabled', false);
                    }
                });
            });
        });
    </script>

    <table class="adminContent">
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.PictureId):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.PictureId)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.PictureId)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.URL):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.URL)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.URL)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.Comment):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.Comment)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.Comment)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.ArabicComment):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.ArabicComment)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.ArabicComment)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.Text):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.Text)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.Text)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.ArabicText):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.ArabicText)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.ArabicText)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.DisplayOrder):
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.AddFeatureItem.DisplayOrder)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.DisplayOrder)
            </td>
        </tr>
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.AddFeatureItem.Visible):
            </td>
            <td class="adminData">
                @Html.CheckBoxFor(model => model.AddFeatureItem.Visible)
                @Html.ValidationMessageFor(model => model.AddFeatureItem.Visible)
            </td>
        </tr>
        <tr>
            <td colspan="2" align="left">
                <input type="button" id="addFeatureListItem" class="k-button" value="@T("Admin.ContentManagement.FeaturesList.AddButton")" />
            </td>
        </tr>
    </table>
}
else
{
    @T("Admin.ContentManagement.FeaturesList.SaveBeforeEdit")
}

Presentation/Nop.Web/Administration/Views/FeaturesList/_CreateOrUpdate.Info.cshtml
@using Nop.Admin.Models.FeaturesLists;

@model FeaturesListModel

@using Nop.Core.Domain.Catalog;
@using Nop.Services.Catalog;
@using System.Text;

<table class="adminContent">
    @if (Model.Id > 0)
    {
        <tr>
            <td class="adminTitle">
                @Html.NopLabelFor(model => model.Id):
            </td>
            <td class="adminData">
                @Model.Id.ToString()
                @Html.ValidationMessageFor(model => model.Id)
            </td>
        </tr>
    }
    <tr>
        <td class="adminTitle">
            @Html.NopLabelFor(model => model.Name):
        </td>
        <td class="adminData">
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>    
</table>